### ISSUE TITLE
snapshot on ImageScrollView visible area 

### ISSUE THREAD

**Issue by hansoong** [dhoerl/PhotoScrollerNetwork#18]
I try the iOS 7 drawViewHierarchyInRect method(very fast) to grab visible area of an ImageScrollView, but it just work in Simulator, not for the device, when UIScrollView back tiling by CATiledLayer.

Example:

UIGraphicsBeginImageContextWithOptions(self.view.bounds.size, NO, [UIScreen mainScreen].scale);

```
    [self.pagingScrollView drawViewHierarchyInRect:self.view.bounds afterScreenUpdates:YES];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
```

My question is, what is the fastest way to create a snapshot(1024 \* 768 maybe) , as this function maybe need to call quick high frequency, like getting pixel rgb value when clicked.

Thanks

hansoong

**Comment by PKPranav** [comment]
Hello hansoong,
My question is, How to call and where "colorAtPosition:" method, to get screen shot of tiled view?

**Comment by hansoong** [comment]
I just download the latest library and take a look, it contains -(UIColor *)getColorAtPosition:(CGPoint)pt
in TilingView.m, which means you need to put this function declaration in TilingView.h.
the pt parameter is the image coordinate, if you image is 8000 * 6000, the the pt value can from
(0,0) to (7999, 5999), 

You may use the UIView function convertPoint like 
self.actualPixelPt = [self.view convertPoint:self.liveTargetView.center toView:tilingView];
or 
self.actualPixelPt = [gestureRecognizer locationInView:tilingView]; 
to get the pt value if you touch view is difference.

after you get the pt, some value between (0, 0) to (7999, 5999) in this example,

you may create some function like below and put in the pt to get the color

-(UIColor *) getColorAtPoint:(CGPoint) pt forScrollView:(ImageScrollView *)iScrollView
{
    TilingView *tilingView = (TilingView *)iScrollView.imageView;
    CGRect rect = CGRectMake(0, 0, tilingView.imageSize.width, tilingView.imageSize.height);
    UIColor *color = nil;
    if(CGRectContainsPoint(rect, pt))
    color = [tilingView getColorAtPosition:pt];
    return color;
}

**Comment by PKPranav** [comment]
Hello hansoong,
Thanks for the quick reply.
I have an image of floor plan and I am adding some pin images as sub view on "imageView" of  ImageScrollView and I have to take screen shot including pin image. Can you explain how to get UIImage for the same.

**Comment by hansoong** [comment]
drawViewHierarchyInRect may not render CATiledLayer class subview in real device, which is your floor plan imageview, you may need to draw and scale each tile in your desire image context.
or you may resize your floor plan image to smaller size that can use original uiimageview to fit in, use that  as a subview instead of the imagescrollview which you need a screen shot.

**Comment by PKPranav** [comment]
Can you give the example and explain ," draw and scale each tile in your desire image context." ?

**Comment by hansoong** [comment]
you may add this kind of function into your TillingView
it will scale down floor plan image to nearly 1024 or 2048 depend on your device.

1024 is just a reference, you can change to any size you want

- (UIImage *)image
{
    float imgScale = 1.0;
    CGRect rect = self.bounds;
    if(MAX(rect.size.width, rect.size.height) > 1024.0)
    {
        float max = MAX(rect.size.width, rect.size.height);
        imgScale = (int) (max / 1024.0 + 0.5);
    }
    NSLog(@"imgScale = %lf", imgScale);
    CGSize size = CGSizeMake(rect.size.width/imgScale, rect.size.height/imgScale);
    
    CGRect bounds = CGRectMake(0, 0, size.width, size.height);
    UIGraphicsBeginImageContextWithOptions(size, YES, 0);
	
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    // get the scale from the context by getting the current transform matrix, then asking for
    // its "a" component, which is one of the two scale components. We could also ask for "d".
    // This assumes (safely) that the view is being scaled equally in both dimensions.
    CGFloat scale = CGContextGetCTM(context).a;
    CATiledLayer *tiledLayer = (CATiledLayer *)[self layer];
    CGSize tileSize = tiledLayer.tileSize;
    // Even at scales lower than 100%, we are drawing into a rect in the coordinate system of the full
    // image. One tile at 50% covers the width (in original image coordinates) of two tiles at 100%.
    // So at 50% we need to stretch our tiles to double the width and height; at 25% we need to stretch
    // them to quadruple the width and height; and so on.
    // (Note that this means that we are drawing very blurry images as the scale gets low. At 12.5%,
    // our lowest scale, we are stretching about 6 small tiles to fill the entire original image area.
    // But this is okay, because the big blurry image we're drawing here will be scaled way down before
    // it is displayed.)
    scale = imgScale;
    tileSize.width /= scale;
    tileSize.height /= scale;
    
    // calculate the rows and columns of tiles that intersect the rect we have been asked to draw
    int firstCol = floorf(CGRectGetMinX(rect) / tileSize.width / scale);
    int lastCol = floorf((CGRectGetMaxX(rect)-1) / tileSize.width / scale);
    int firstRow = floorf(CGRectGetMinY(rect) / tileSize.height / scale);
    int lastRow = floorf((CGRectGetMaxY(rect)-1) / tileSize.height / scale);
    
    for (int row = firstRow; row <= lastRow; row++)
    {
        [self.delegate showProgress:(row+0.0f)/(lastRow+1)];
        for (int col = firstCol; col <= lastCol; col++)
        {
            CGRect tileRect = CGRectMake(tileSize.width * col, tileSize.height * row,
                                         tileSize.width + 1, tileSize.height + 1);
            // if the tile would stick outside of our bounds, we need to truncate it so as to avoid
            // stretching out the partial tiles at the right and bottom edges
            tileRect = CGRectIntersection(bounds, tileRect);
			if(!tileRect.size.width || !tileRect.size.height)
            { LOG(@"WTF"); continue; }
			
            //UIImage *tile = [tb tileForScale:scale row:row col:col];
            UIImage *tile = [tb tileForScale:scale location:CGPointMake(col, row)];
            [tile drawInRect:tileRect];
            
            if (self.annotates) //if((row == lastRow) || (col == lastCol))
            {
                [[UIColor whiteColor] set];
                CGContextSetLineWidth(context, 6.0 / scale);
                CGContextStrokeRect(context, tileRect);
            }
        }
    }

    UIImage *img = UIGraphicsGetImageFromCurrentImageContext();

    UIGraphicsEndImageContext();

    return img;
}

**Comment by dhoerl** [comment]
I realize that this is 7 years old, but the iOS advancement in iOS 7 made this easily doable:
  drawViewHierarchyInRect

Anyway, fixed in the new Swift Package.
