### ISSUE TITLE
Cancel TileImageBuilder

### ISSUE THREAD

**Issue by HomeSchoolDev** [dhoerl/PhotoScrollerNetwork#21]
Hi,

I was looking through your code, but did not see a way to cancel the tiling. 

I noticed the you have ConcurrentOp, but it looks like that was made for fetching images from the web and then tiling. My images are local, but I'm still needing to be able to cancel the image tiler. I'm creating the image tiler lazily on a per page basis. If there user is paging very quickly I need to be able to stop the tiler instantly when the page leaves the bounds of the screen. If I don't the tilers start piling up in the queue and bring my phone to a halt.

Thanks!

**Comment by dhoerl** [comment]
A cancel() method has been added to the Swift Package version. It will halt any operations in progress as well as shut down the rest of the app.
