### ISSUE TITLE
Using libjpeg on arm64

### ISSUE THREAD

**Issue by chrisheid** [dhoerl/PhotoScrollerNetwork#22]
Hi, I'm trying to integrate PhotoScrollerNetwork into an application I'm writing. The demo works great but our targets include arm64 iPads. This means that using the jpeglib included in the build doesn't work. I read in previous issues that you were trying to build an updated version. Did you have any luck? Thanks in advance!

**Comment by dcommander** [comment]
libjpeg-turbo 1.4.0 now properly supports ARM64 and includes ARM64 architectures in all of the binaries installed by the DMG file:
http://sourceforge.net/projects/libjpeg-turbo/files/1.4.0/
