### ISSUE TITLE
cocoapod

### ISSUE THREAD

**Issue by tcurdt** [dhoerl/PhotoScrollerNetwork#23]
Would be nice to turn this into a Pod.

**Comment by SiMet** [comment]
I'd like to also ask about Pod

**Comment by dhoerl** [comment]
The problem is that the library depends on libjpeg-turbo, and there is no pod for that. So right now the project builds both. I have considered doing a pod myself for libjpeg-turbo, but just haven't gotten to it (its a big job).

**Comment by SiMet** [comment]
Could you create pod not for libjpeg-turbo but project which use this as pod but just included lib?

**Comment by tcurdt** [comment]
@dhoerl close without comment?

**Comment by dhoerl** [comment]
The updated README explains that I'm in the process of converting this to a Swift Package. I myself will never make a CocoaPod of it.

**Comment by dhoerl** [comment]
The Swift Package is now out - first version - and a test app too.
