### ISSUE TITLE
Xcode 6 Simulator Link Issue

### ISSUE THREAD

**Issue by Robbeh13** [dhoerl/PhotoScrollerNetwork#24]
Thanks very much for the project. It's been very, very helpful. Will you have time to update to Xcode 6? I've attempted to work with it, but receive linker messages when attempting to use it with the simulator:

Undefined symbols for architecture i386:
  "_putenv$UNIX2003", referenced from:
      _tjTransform in libturbojpeg.a(libturbojpeg_la-turbojpeg.o)
      _tjDecompressToYUV in libturbojpeg.a(libturbojpeg_la-turbojpeg.o)
      _tjDecompress2 in libturbojpeg.a(libturbojpeg_la-turbojpeg.o)
      _tjEncodeYUV2 in libturbojpeg.a(libturbojpeg_la-turbojpeg.o)
      _tjCompress2 in libturbojpeg.a(libturbojpeg_la-turbojpeg.o)
ld: symbol(s) not found for architecture i386

It will still run fine if debugging on a device, just not the simulator. There were no problems with Xcode 5.

I'm not sure where to begin with troubleshooting this issue. Is this something DRCommander needs to address (will he be wiling?), or is it something that can be fixed by configuring Xcode and not involving the libturbojpeg team? Perhaps the issue lies with me (although I've tried cleaning the build directories and recompiling the headers)?

Thanks for you time,
-Rob

**Comment by dhoerl** [comment]
I forget the exact fix, but the libjpeg-turbo developer (DRC) found the correct flag for building the library, and this issue is now fixed.

**Comment by Robbeh13** [comment]
Thanks very much!
