### ISSUE TITLE
ALAsset?

### ISSUE THREAD

**Issue by fishandphil** [dhoerl/PhotoScrollerNetwork#29]
Hi dhoerl,

I am trying to understand how you'd adapt the code to efficiently handle pictures coming from the camera roll? 

I believe we cannot use CGImageSourceCreateWithURL with ALAsset.
I am looking at loading large images like panoramic; whenever I try to access the ALAsset.defaultRepresentation.fullResolutionImage with a paranoramic image (13000x2800); I get shut down because of memory. 

Would you recommend something like the following to get my hand on the CGImageSource? : 

```
ALAssetRepresentation *rep = [asset defaultRepresentation];
CGDataProviderDirectCallbacks callbacks = {
    .version = 0,
    .getBytePointer = NULL,
    .releaseBytePointer = NULL,
    .getBytesAtPosition = getAssetBytesCallback,
    .releaseInfo = releaseAssetCallback,
};
CGDataProviderRef provider = CGDataProviderCreateDirect((void *)CFBridgingRetain(rep), [rep size], &callbacks);
CGImageSourceRef source = CGImageSourceCreateWithDataProvider(provider, NULL);
```

Thank you very much. Appreciate your expertise on this.
Regards

**Comment by dhoerl** [comment]
I have no experience with the Camera Roll so cannot provide specific info. However, note that this library is designed to load files that are received over a network connection. Several months ago a few people showed interest in modifying it to use local files instead. I wrote up something telling them the steps I believed would be required to do it. This is not a trivial modification, and there has been no more posts by those people so I don't know if they managed to modify the library in a fork or not (I suspect not).

Obviously you could do this yourself but as I alluded to, its not going to be a trivial exercise.

**Comment by dhoerl** [comment]
I realize this is 4 years later, but I'm turning this project into a Swift Package, and will look to support this feature.

**Comment by dhoerl** [comment]
Swift Package is now done. Can look at this if you are still interested. The package version uses a NSOutputStream interface - so it consumes small chunks of data as provided by the input stream. Should be possible (easy?) to use a image source.

**Comment by dhoerl** [comment]
I have a larger panoramic image on my phone, no problem looking at it, even in a 6s phone. Don't think this is going to be an issue anymore.
