### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by amarcus** [dhoerl/PhotoScrollerNetwork#32]
Hi, and thank you for your lib!

I've come with a problem, on the simulator everything works really nice and no problem with huge images at all.

But on the real device (iPhone 6, iOS 10) when trying to load Space_4 or Space_6 I'm getting an error PhotoScrollerNetwork[16434:4970618] Warning: cannot F_PREALLOCATE for input file (errno No space left on device). That's strange, because I have 8 GB of free space on my phone.

I'm not sure that the problem is here. After that warning I also get more.

PhotoScrollerNetwork[16434:4970553] YIKES LOW MEMORY: ubc_threshold=476469248 ubc_usage=0
PhotoScrollerNetwork[16434:4970553] Yikes!:   total: 594276352 used: 589619200 FREE: 4657152   [resident=125038592 virtual=2579480576]
2017-09-29 05:43:08.870638+0300 PhotoScrollerNetwork[16434:4970553] Yikes! ViewController didReceiveMemoryWarning!
2017-09-29 05:43:08.870693+0300 PhotoScrollerNetwork[16434:4970553] Yikes! PhotoViewController didReceiveMemoryWarning!
Message from debugger: Terminated due to memory issue

But, you write you tested it on iPhone 4 with much less memory and it worked... I changed nothing after downloading the lib, just trying to run it. So, it should work on iPhone 6, isn't it? Am I doing something wrong or something wrong with my device? Any ideas?

Thank you in advance!

Andrew.

**Comment by dhoerl** [comment]
I have a 6s+ but its now on iOS 11. Traveling now but could try it later if need be. What I suggest you do is comment out the F_PREALLOCATE  flag and try again - the whole idea is to insure you have sufficient space before even attempting to spend the bandwidth downloading a massive image. Its quite possible that Apple changed how the file system worked - they changed the file system to APFS (something like that) in iOS 10 as I recall.

**Comment by dhoerl** [comment]
So I just updated the code. The bottom line is that F_ALLOCATECONTIG plus F_PREALLOCATE work differently. Have a question into Apple about it, but for now change F_ALLOCATECONTIG to 0 and all is well. I tested on an iOS10 12" iPad running iOS 10 - my other devices are iOS 11 now.
